packages:
  - 'packages/bible'
  - 'packages/scripts'
  - 'packages/__tests__/roject1'
  - 'apps/src-tauri'
  - 'apps/web'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true

nodeLinker: hoisted

minimumReleaseAge: 300

minimumReleaseAgeExclude:
  - '@bemedev/*'
