/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderVersionBookChapterRouteImport } from './routes/reader/$version/$book/$chapter'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderVersionBookChapterRoute =
  ReaderVersionBookChapterRouteImport.update({
    id: '/reader/$version/$book/$chapter',
    path: '/reader/$version/$book/$chapter',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/reader/$version/$book/$chapter': typeof ReaderVersionBookChapterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/reader/$version/$book/$chapter': typeof ReaderVersionBookChapterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/reader/$version/$book/$chapter': typeof ReaderVersionBookChapterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/reader/$version/$book/$chapter'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/reader/$version/$book/$chapter'
  id: '__root__' | '/' | '/reader/$version/$book/$chapter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReaderVersionBookChapterRoute: typeof ReaderVersionBookChapterRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$version/$book/$chapter': {
      id: '/reader/$version/$book/$chapter'
      path: '/reader/$version/$book/$chapter'
      fullPath: '/reader/$version/$book/$chapter'
      preLoaderRoute: typeof ReaderVersionBookChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReaderVersionBookChapterRoute: ReaderVersionBookChapterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
